class:
    dataset: "TextDataset"
    model: "ReGVD"
    optimizer: "AdamW"
dataset:
    file_path: <YOUR_PATH>
    test_split: 0.2
    data_format: "json"
    code_field: "func"
    label_field: "target"
model:
    transformer:
        model_name_or_path: "microsoft/codebert-base"
        do_lower_case: False
    gnn: "ResGatedGNN"
    window_size: 5
    remove_residual: False
    att_op: "mul"
    hidden_size: 256
    feature_size: 768
    num_classes: 2
    num_gnn_layers: 2
optimizer:
    lr_scheduler:
        type: "linear"
    lr: 0.0005
    weight_decay: 0.0
    eps: 0.00000001
runner:
    train_batch_size: 128
    eval_batch_size: 128
    num_train_epochs: 30
    max_grad_norm: 1.0
seed: 42
