class:
    dataset: 'TextDataset'
    model: 'ReGVD'
    optimizer: 'AdamW'
dataset:
    file_path: 'data/devign/devign.json'
    file_type: 'json'
    validate_split: 0.2
model:
    transformer:
        model_name_or_path: 'microsoft/codebert-base'
        config_name: ''
        tokenizer_name: ''
        do_lower_case: False
    gnn: 'ResGatedGNN'
    window_size: 5
    remove_residual: False
    att_op: 'mul'
    hidden_size: 256
    feature_size: 768
    num_classes: 2
    num_gnn_layers: 2
optimizer:
    scheduler:
        type: 'linear'
        num_warmup_steps: -1
    lr: 0.0005
    weight_decay: 0.0
    eps: 0.00000001
train:
    batch_size: 128
    epochs: 30
    save_per_steps: -1
    log_per_steps: -1
    max_grad_norm: 1.0
eval:
    batch_size: 128
seed: 42
